### ISSUE TITLE
Unable to install metasploit on Ubuntu 16.04 and 17.04 : "E: Unable to locate package metasploit-framework"

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#313]
`ptf` is unable to install `metasploit` on my Ubuntu 16.04 and 17.04, because it can't locate the package `metasploit-framework`. It gives me this error : 
>E: Unable to locate package metasploit-framework

So there is clearly a problem with this `metasploit` repository.

**Comment by BustedSec** [comment]
is the a fresh install of PTF or an older on you're trying to update?

**Comment by sidahmed-malaoui** [comment]
On a fresh install on my Ubuntu 17.04, it give me the error : 
>E: Unable to locate package metasploit-framework

And when I try to update on my Ubuntu 16.04 (it is already installed), it give me the error : 
>Reinstallation of metasploit-framework is not possible, it cannot be downloaded.

**Comment by jeffmcjunkin** [comment]
FWIW I couldn't replicate the issue in a fresh Ubuntu 16.04 x64 install as of this morning. `msfconsole` ran fine after install:

https://pastebin.com/fLZNAaUW

Given the issue description it sounds like there was an issue adding the metasploit apt repository, but I don't know what caused it.

An internal project seems to have had the same issue, but maybe it was solved?

**Comment by sidahmed-malaoui** [comment]
The pastbin file you provided is having the same issue : 
![ptf](https://cloud.githubusercontent.com/assets/19175347/26118598/cefb1150-3a6a-11e7-98a9-2cecbd4de01b.png)

Look at the line 596 in your pastbin file, it says : 
>E: Unable to locate package metasploit-framework

So I guess that metasploit is already installed in your system, that's why you didn't notice the error.

**Comment by jeffmcjunkin** [comment]
Ah! That VM wasn't as clean as I thought. I'll give it a show with an _actually_ fresh install. Thanks!

**Comment by jeffmcjunkin** [comment]
New pastebin a newly-installed-from-ISO VM: https://pastebin.com/LPqbhPXL

Looks like AFTER_COMMANDS tries to install metasploit-framework before the repository is properly added, but `./msfinstall` does install it correctly.

**Comment by sidahmed-malaoui** [comment]
First, thanks for taking this issue seriously, that's very professional.

Second, I thought that the problem that `ptf` isn't updating the packages cache (`apt update`). So what I've tried to update it manually with the command `sudo apt update`, and even after that, my package manager can't find the package `metasploit-framework`.

So I've opened the file `/etc/apt/sources.list.d/metasploit-framework.list` and grabed the link to the `metasploit` repository [http://downloads.metasploit.com/data/releases/metasploit-framework/apt](http://downloads.metasploit.com/data/releases/metasploit-framework/apt). I tried to get in the multiple subdirectories, and they all give me this message : 
>File not found."

So I guess that the problem is this metasploit repository, may be they changed it or something like that.

**Comment by jeffmcjunkin** [comment]
From my fresh VM:
```
root@ubuntu:~# cat /etc/apt/sources.list.d/metasploit-framework.list 
deb http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main
```

Then browsing to the actual URL:
http://downloads.metasploit.com/data/releases/metasploit-framework/dists/lucid/main/binary-amd64/Packages

Looks like there's probably an upstream issue after all. I'll raise it with them.

**Comment by jeffmcjunkin** [comment]
The plot thickens:

```
root@ubuntu:~# apt download metasploit-framework --print-uris
'http://downloads.metasploit.com/data/releases/metasploit-framework/apt/pool/main/m/metasploit-framework/metasploit-framework_4.14.18+20170516093030~1rapid7-1_amd64.deb' metasploit-framework_4.14.18+20170516093030~1rapid7-1_amd64.deb 173065244 SHA256:adbd4692555b2ca9a1b4526bf8d649ccb634244c5104f6bdeeb82e4de6bc62a2
```
And I can download that URL.

**Comment by sidahmed-malaoui** [comment]
@jeffmcjunkin That's weird, now `ptf` is installing `metasploit-framework` !

May be they fixed their repository !

**Comment by jeffmcjunkin** [comment]
Weird. I didn't get a reply in Metasploit's IRC, and it's working now... so let's chalk it up to weirdness and close this issue. @BustedSec can we call this one done?

**Comment by BustedSec** [comment]
I think so, just conducting a little more investigation using different ubuntu vm's to make sure issue is resolved before recommending closing

**Comment by BustedSec** [comment]
ok, tested on fresh installs of 15.04, 16.04 and 17.04 with only git and python installed. No installation issues with metasploit could be replicated. Looks like it was probably a temporary issue with the http://downloads.metasploit.com server - perhaps they were doing maintenance. Since this issue is resolved for the OP and testing confirms it's not being replicated I agree with @jeffmcjunkin  that this issue be closed.

**Comment by tkh16** [comment]
This seems to have started happening again, as of today (it worked fine yesterday).

```
[*] Sending after command: apt-get install --reinstall metasploit-framework
[...]
E: Unable to locate package metasploit-framework
```

I also see the other symptoms described above (I work with @jeffmcjunkin on the same internal project he mentioned), leading me to believe this is the same issue again.

**Comment by BustedSec** [comment]
Please try the following wget -O -
http://apt.metasploit.com/metasploit-framework.gpg.key | sudo apt-key add -
then rerun the module

**Comment by tkh16** [comment]
Just tried that, still get the same results: failed install, with the error `E: Unable to locate package metasploit-framework` appearing a few times.

**Comment by BustedSec** [comment]
what are the contents of your etc/apt/sources.list 
also have you tried references in it to metasploit in sources.list, run an apt-get update, then re-run  the ptf module

**Comment by sidahmed-malaoui** [comment]
I confirm, I've got this error again too.

**Comment by tkh16** [comment]
I see the following in `/etc/apt/sources.list.d`:
`deb http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main`

I can attach the entire contents if you'd like, but I'm guessing that's the important part.

I also tried running `apt-get update` and re-running the module, to no avail.

I suspect this might be an upstream issue...that the package you're depending on isn't there for some reason, maybe?  I'm seeing the same `File not found."` behavior that my colleague @jeffmcjunkin mentioned earlier.

**Comment by BustedSec** [comment]
Confirmed. Something is breaking down when it tried to grab the stuff from http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main
looks like it's getting a file not found. Also tried doing a curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall &&   chmod 755 msfinstall &&   ./msfinstall and got the same result. Looks like Rapid7 is messing with stuff again.

**Comment by BustedSec** [comment]
if you are in a rush, you can grab the deb installer from here for your arch https://apt.metasploit.com/ until they resolve this

**Comment by BustedSec** [comment]
looks like the links are broken right off their nightly build page as well https://apt.metasploit.com/

**Comment by BustedSec** [comment]
submitted issue with rapid7 https://github.com/rapid7/metasploit-framework/issues/8454

**Comment by BustedSec** [comment]
Rapid7 reports issue is fixed on their end now. Will test again in a few mins.

**Comment by BustedSec** [comment]
OK, we are back in business. Confirmed working now on 16.04 and 16.10. Issue can be closed.

**Comment by tkh16** [comment]
Confirmed working for me as well...thank you!

**Comment by mattulm** [comment]
hello, still seem to have an issue with the updates:

E: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/main/binary-amd64/Packages  Hash Sum mismatch

Any thoughts or suggestions?

**Comment by jeffmcjunkin** [comment]
Happened to me once recently. Worked on the second try. I think it's still
possible to attempt a download while Rapid7 is syncing that folder.

**Comment by Luckytrang2010** [comment]
there isn't a problem in the repository
> E: Unable to locate package metasploit-framework

if you see this...

> Adding metasploit-framework to your repository list..E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

just install `gnupg` and you're good to go

**Comment by pietrotedeschi** [comment]
If you receive the following error ```E: Unable to locate package metasploit-framework``` after ```sudo ./msfinstall```, you need to update your package list list with ```sudo apt-get update```.

**Comment by BustedSec** [comment]
yeah, I think we should just add sudo apt-get update to the after-commands to avoid people running into this, it'll only add a few secs to a standard install

**Comment by BustedSec** [comment]
https://github.com/trustedsec/ptf/compare/master...BustedSec:patch-3

**Comment by x4cx69x65** [comment]
> 
> 
> `ptf` is unable to install `metasploit` on my Ubuntu 16.04 and 17.04, because it can't locate the package `metasploit-framework`. It gives me this error :
> 
> > E: Unable to locate package metasploit-framework
> 
> So there is clearly a problem with this `metasploit` repository.

Install one of these packets gnupg, gnupg2, gnupg1 it should work then
